// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnxqNmdC89Fmwt3P9ByS0-phQVg1z-x4k',
    appId: '1:486330825420:web:8134b6ab5223b24c1c6069',
    messagingSenderId: '486330825420',
    projectId: 'fallapp-892d2',
    authDomain: 'fallapp-892d2.firebaseapp.com',
    storageBucket: 'fallapp-892d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9A7E8iV-B0ugniGi6Abe9uD_eg4a8w6I',
    appId: '1:486330825420:android:5884e6bc74be30821c6069',
    messagingSenderId: '486330825420',
    projectId: 'fallapp-892d2',
    storageBucket: 'fallapp-892d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcI_tw70evSlLn_0XIKVrrK_WYX_UYUIU',
    appId: '1:486330825420:ios:e909ece61ff9fe741c6069',
    messagingSenderId: '486330825420',
    projectId: 'fallapp-892d2',
    storageBucket: 'fallapp-892d2.appspot.com',
    iosClientId:
        '486330825420-3kvfi56477jg9d2p8b6jsk3slmutiloc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fallAppRemaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcI_tw70evSlLn_0XIKVrrK_WYX_UYUIU',
    appId: '1:486330825420:ios:e909ece61ff9fe741c6069',
    messagingSenderId: '486330825420',
    projectId: 'fallapp-892d2',
    storageBucket: 'fallapp-892d2.appspot.com',
    iosClientId:
        '486330825420-3kvfi56477jg9d2p8b6jsk3slmutiloc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fallAppRemaster',
  );
}
